version: "3"
services:
  car-rental-db:
    image: mariadb:10.5
    container_name: car-rental-db
    volumes:
      - "/home/dionis/_bootcamp/CarRental/docker-containers/db:/var/lib/mysql"
      - "/home/dionis/_bootcamp/CarRental/docker-containers/db/config:/etc/mysql/conf.d"
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - car_rental-network
    restart: unless-stopped

  car-rental-api:
    image: amoraresco/it-academy-project:latest
    container_name: car-rental-api
    links:
      - car-rental-db
      - car-rental-redis
    ports:
      - "88:80"
      - "882:22"
    volumes:
      - "/home/dionis/_bootcamp/CarRental:/var/www/html"
    environment:
      - APP_URL=http://myproject.com
      - MAIL_HOST=car-rental-mailhog
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_PORT=1025
      - MAIL_FROM_ADDRESS=moraresco.andrian@gmail.com
      - MAIL_NAME="PHR API"
      - MAIL_DELAY=2500
      - DB_HOST=car-rental-db
      - DB_DATABASE=car_rental_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=3306
    networks:
      - car_rental-network
    restart: unless-stopped

  car-rental-mailhog:
    image: mailhog/mailhog
    container_name: car-rental-mailhog
    ports:
      - "8825:8025"
      - "8125:1025"
    networks:
      - car_rental-network

  car-rental-redis:
    image: redis:3.0
    container_name: car-rental-redis
    volumes:
      - "/home/dionis/_bootcamp/CarRental/docker-compose/redis/cache/data:/data"
    ports:
      - "8379:6379"
    restart: unless-stopped
    networks:
      - car_rental-network

networks:
  car_rental-network:
    driver: bridge
